Feature/rtodling/v1 5 4 onl xoffl flags
GEOS-ESM/GEOSgcm_App pull request #265
Opened 2021-10-30 10:38 UTC by rtodling

We've had the issue of having mixed variable definition between what's to be handled at setup and what's to be handled at run time for quite sometime. The bottom line is this: 

variables labeled @SOMETHING are setup variables
variable labeled >>>SOMETHING<<< are run-time vars

The DAS does not mix them, but the GCM unfortunately does. The present changes makes a minor contribution toward adjusting these on the GCM side for two variables:

COUPLED
DATAOCEAN

The changes here also add a variable CLDMICRO that defines the micro physics opt used - defaults to 1MOMENT -  and only in COUPLED mode it is redefined as 2MOMENT; that is, this is no longer wired in the COUPLED section of the AGCM.rc.tmpl - since we want to ability to decide the micro physic opt at setup time for the couple case.

Notice that there seems to be already a conflict - not introduced by these changes - in the setup  where there seems to be two ways of controlling the microphysics options: 

a) one is controlled by the variable CLDMICRO of the AGCM.rc.tmpl - not to be confused w/ the script variable I introduced of the same name (for consistency) --- this option is triggered when setting up a COUPLED exp.
b) and another called: MP_MG1CLDMICRO - which is present in both AMIP and COUPLED modes

How (in)consistent these are in the setup and how these interact in the model is beyond me.

In any case, the changes here to do fuss w/ trying to address spotted inconsistencies. I simply coordinates var names between the model and DAS setups. All changes should be zero diff and have the intent to allow the ADAS to setup a coupled run optio,  which it now does.

2021-11-01 12:43 UTC, mathomp4 commented on AGCM.rc.tmpl
> +CICE4_IMPORT_RESTART_FILE:             seaice_import_rst
@rtodling These might need to be `@COUPLED` protected.

2021-11-04 13:35 UTC, sanAkel commented on AGCM.rc.tmpl
> +CICE4_IMPORT_RESTART_FILE:             seaice_import_rst
Does "@a" work the same way as ">>>" If so I *prefer former* - it is less stuff to type and look at!

2021-11-04 13:37 UTC, sanAkel commented on AGCM.rc.tmpl
>  >>>MOM5<<<#DATA_SST_FILE: sst.data
@MOM5 for these two lines

2021-11-04 13:39 UTC, sanAkel commented on gcm_forecast.tmpl
>  >>>MOM6<<<setenv GRIDDIR  @COUPLEDIR/MOM6/@ATMOStag_@OCEANtag
@MOM5 *and* @MOM6

2021-11-04 13:41 UTC, sanAkel commented on gcm_run.j
>  >>>MOM5<<</bin/ln -s @COUPLEDIR/a@HIST_IMx@HIST_JM_o${OGCM_IM}x${OGCM_JM}/DC0@HIST_IMxPC0@HIST_JM_@OCEANtag-Pfafstetter.til tile_hist.data
@MOM5

2021-11-04 13:45 UTC, sanAkel commented on gcm_setup
>  s?>>>MOM5<<<?$MOM5?g
@MOM5 and @MOM6

2021-11-04 13:45 UTC, sanAkel commented on gcm_setup
> +s?@COUPLED?$COUPLED?g
@COUPLED

2021-11-04 13:46 UTC, sanAkel requested changes
needs testing ...

2021-11-04 13:46 UTC, mathomp4 commented on AGCM.rc.tmpl
> +CICE4_IMPORT_RESTART_FILE:             seaice_import_rst
My main question was is it okay to have these not be protected by `@COUPLED`. I suppose it is, I mean, other restarts are exposed at all times...

2021-11-04 13:57 UTC, yvikhlya commented on gcm_run.j
>  >>>MOM6<<< set dsets="ocean_state prog_z sfc_ave forcing"
> What if I prefer to call `prog_z` in _my version_ of `diag_table` `prog_z_WOA`?

Then you need to make a suggestion, how gcm_run script is supposed to know which files to copy.

2021-11-04 14:03 UTC, sanAkel commented on gcm_run.j
>  >>>MOM6<<< set dsets="ocean_state prog_z sfc_ave forcing"
something to the following effect:

set `mom_output_file_names = x1, x2, x3, ...` does that work for you? Please, *again* in a *LATER* PR. Thanks!

2021-11-09 16:34 UTC, mathomp4 approved these changes
Tested with AMIP, MOM5, MOM6. All seemed to run and were zero-diff.

2021-11-09 16:37 UTC, sanAkel approved these changes
All requested changes seem to have been made. We have to test the new `1440x1080` configuration.

2021-11-09 18:42 UTC, merged