Adding Data Atmosphere from S2S to mainline gcm
GEOS-ESM/GEOSgcm_App pull request #668
Opened 2024-12-11 19:04 UTC by sshakoor1

The purpose of this PR is add add a new question to `gcm_setup` for data atmosphere when running coupled. This originates from `GEOS-S2S-3`(https://github.com/GEOS-ESM/GEOS-S2S-3/pull/15), and as per request of @mfmehari it is being added to the main gcm.

2024-12-11 23:25 UTC, mathomp4 commented on gcm_setup
> +set MPI_STACK = intelmpi
@sshakoor1 Uh oh. It looks like the CMake `@FOO@` bits got lost. Can you restore them?

2024-12-12 13:44 UTC, mathomp4 commented on linkbcs.tmpl
> +@ACTUAL_ATM4OCN/bin/ln -sf /discover/nobackup/projects/gmao/ssd/aogcm/atmosphere_bcs/JRA55-DO ExtData
This needs to be fixed somehow. At the moment, this breaks the model on any machine that is not NCCS since it has a fixed path to discover disks. I'm going to block this PR until we can fix this.

@zhaobin74 @mfmehari Are these boundary conditions? Or are they more like Chemistry ExtData? 

If the former, we should work with @biljanaorescanin to get it into the new BCS location (such as /discover/nobackup/projects/gmao/bcs_shared/fvInput/ExtData/esm on discover, etc.)

If the latter, then they probably should go into the Ops ExtData area managed by @rlucches and @mssolomo 

No matter what, we also have the issue that it is ~1.5 TB in size. So perhaps that might determine that they go in the @biljanaorescanin space as it might have more room? I'm not sure.

2024-12-12 14:19 UTC, zhaobin74 commented on linkbcs.tmpl
> +@ACTUAL_ATM4OCN/bin/ln -sf /discover/nobackup/projects/gmao/ssd/aogcm/atmosphere_bcs/JRA55-DO ExtData
I think it is more like boundary conditions, so should go with  @biljanaorescanin. The data can be relocated to their proper locations. 

However, this line should be something like
```@ACTUAL_ATM4OCN/bin/ln -sf /discover/nobackup/projects/gmao/ssd/aogcm/ocean_bcs/* ExtData```
because we may have more sources of data in future e.g. ERA5. This way all sources will be mapped.

2024-12-12 14:42 UTC, biljanaorescanin commented on linkbcs.tmpl
> +@ACTUAL_ATM4OCN/bin/ln -sf /discover/nobackup/projects/gmao/ssd/aogcm/atmosphere_bcs/JRA55-DO ExtData
Whole idea of `bcs_shared` is that we don't have more spaces that say in path this: `ocean_bcs` or `atmosphere_bcs`.  All BCs should be at same location. And not scattered on discover. 

I will add them here for now, since we have surface specific areas there, I hope that works for everyone? 
`/discover/nobackup/projects/gmao/bcs_shared/make_bcs_inputs/seaice/JRA55-DO`

@zhaobin74 I will need readme file explaining what these are and difference for 2 directories.  To add to file directory. We can't merge this PR before that.

2024-12-12 14:49 UTC, mathomp4 commented on linkbcs.tmpl
> +@ACTUAL_ATM4OCN/bin/ln -sf /discover/nobackup/projects/gmao/ssd/aogcm/atmosphere_bcs/JRA55-DO ExtData
Note @zhaobin74 as well. Once the final resting place is known, the ExtData yaml file might need to be changed. Since the path might be slightly different depending on how things get moved around.

2024-12-12 14:54 UTC, mfmehari commented on linkbcs.tmpl
> +@ACTUAL_ATM4OCN/bin/ln -sf /discover/nobackup/projects/gmao/ssd/aogcm/atmosphere_bcs/JRA55-DO ExtData
> Note @zhaobin74 as well. Once the final resting place is known, the ExtData yaml file might need to be changed. Since the path might be slightly different depending on how things get moved around.

@mathomp4 @zhaobin74 yes we will edit it accordingly if there are some changes to path of the dataset.
As far as it stays like this ExtData/JRA55-DO/* ... then it is okay.

2024-12-12 14:56 UTC, zhaobin74 commented on linkbcs.tmpl
> +@ACTUAL_ATM4OCN/bin/ln -sf /discover/nobackup/projects/gmao/ssd/aogcm/atmosphere_bcs/JRA55-DO ExtData
@biljanaorescanin, these data are not for sea ice alone. I would propose the location for JRA55-DO to be
```/discover/nobackup/projects/gmao/bcs_shared/make_bcs_inputs/oceanice/dataatm/JRA55-DO```

But the linkbcs should use
```@ACTUAL_ATM4OCN/bin/ln -sf /discover/nobackup/projects/gmao/bcs_shared/make_bcs_inputs/oceanice/dataatm/* ExtData```

such that
```/discover/nobackup/projects/gmao/bcs_shared/make_bcs_inputs/oceanice/dataatm/ERA5``` in future can also be made available without changing linkbcs anymore.

2024-12-12 15:00 UTC, mathomp4 commented on linkbcs.tmpl
> +@ACTUAL_ATM4OCN/bin/ln -sf /discover/nobackup/projects/gmao/ssd/aogcm/atmosphere_bcs/JRA55-DO ExtData
Hmm. Are these for Data Atm? If so, then I think the detemplate name is wrong. The way this is set up, it would be used for Actual Atm, not Data Atm. (Since `@ACTUAL_ATM4OCN` is `#` for Data Atm and `<empty string>` for Actual Atm.

2024-12-12 15:11 UTC, zhaobin74 commented on linkbcs.tmpl
> +@ACTUAL_ATM4OCN/bin/ln -sf /discover/nobackup/projects/gmao/ssd/aogcm/atmosphere_bcs/JRA55-DO ExtData
> > Note @zhaobin74 as well. Once the final resting place is known, the ExtData yaml file might need to be changed. Since the path might be slightly different depending on how things get moved around.
> 
> @mathomp4 @zhaobin74 yes we will edit it accordingly if there are some changes to path of the dataset. As far as it stays like this ExtData/JRA55-DO/* ... then it is okay.

We don't need to change if you use
```@ACTUAL_ATM4OCN/bin/ln -sf /discover/nobackup/projects/gmao/bcs_shared/make_bcs_inputs/oceanice/* ExtData```

2024-12-12 15:14 UTC, zhaobin74 commented on linkbcs.tmpl
> +@ACTUAL_ATM4OCN/bin/ln -sf /discover/nobackup/projects/gmao/ssd/aogcm/atmosphere_bcs/JRA55-DO ExtData
> > Hmm. Are these for Data Atm? If so, then I think the detemplate name is wrong. The way this is set up, it would be used for Actual Atm, not Data Atm. (Since `@ACTUAL_ATM4OCN` is `#` for Data Atm and `<empty string>` for Actual Atm.
> 
> Yeah, that's right @mathomp4 it should be removed or I think replaced by @coupled

What does ```@ACTUAL_ATM4OCN``` mean?

2024-12-12 15:14 UTC, mfmehari commented on linkbcs.tmpl
> +@ACTUAL_ATM4OCN/bin/ln -sf /discover/nobackup/projects/gmao/ssd/aogcm/atmosphere_bcs/JRA55-DO ExtData
@zhaobin74 @ACTUAL_ATM4OCN is '#' when DataAtm is running, i.e the line will be commented if DataAtm is on.

2024-12-12 15:35 UTC, mfmehari commented on linkbcs.tmpl
> +@ACTUAL_ATM4OCN/bin/ln -sf /discover/nobackup/projects/gmao/ssd/aogcm/atmosphere_bcs/JRA55-DO ExtData
@mathomp4 @sshakoor1 the questions for Land and GOCART are still there when DataAtm is switched on ... let me see if I can suppress them.

2024-12-12 15:43 UTC, zhaobin74 requested changes
This should be 
```@COUPLED/bin/ln -sf $BOUNDARY_DIR/bcs_shared/make_bcs_inputs/oceanice/* ExtData```

2024-12-12 15:49 UTC, mfmehari commented
> This should be `@COUPLED/bin/ln -sf $BOUNDARY_DIR/bcs_shared/make_bcs_inputs/oceanice/* ExtData`

@zhaobin74 done!

2024-12-12 17:07 UTC, mathomp4 commented on linkbcs.tmpl
> +@COUPLED/bin/ln -sf $CPLDIR/dataatm/* ExtData
```suggestion
@COUPLED/bin/ln -sf $COUPLEDIR/dataatm/* ExtData
```

Turns out `CPLDIR` is something different (it goes down into `ocean/` further.

2024-12-12 17:34 UTC, zhaobin74 submitted a review, later dismissed
all good. thanks.

2024-12-12 18:09 UTC, biljanaorescanin commented
Did anyone run a test? 
fyi I've added readme Bin gave me to dataatm path. 
`/discover/nobackup/projects/gmao/bcs_shared/make_bcs_inputs/ocean/dataatm`

2024-12-12 18:12 UTC, mfmehari commented
> Did anyone run a test? fyi I've added readme Bin gave me to dataatm path. `/discover/nobackup/projects/gmao/bcs_shared/make_bcs_inputs/ocean/dataatm`

@biljanaorescanin in the processes of testing it.

2024-12-12 18:45 UTC, mathomp4 commented
Note: The CI failures are because of the new question. Once @mfmehari says it works, then I can try figuring out how to get my scripts to work.

2024-12-12 22:34 UTC, mfmehari commented
> > Did anyone run a test? fyi I've added readme Bin gave me to dataatm path. `/discover/nobackup/projects/gmao/bcs_shared/make_bcs_inputs/ocean/dataatm`
> 
> @biljanaorescanin in the processes of testing it.

@biljanaorescanin the new location/directory path for JRA55-DO works.

2024-12-13 21:02 UTC, mfmehari submitted a review, later dismissed

2025-01-03 16:52 UTC, mfmehari commented
@mathomp4 @sshakoor1 @sdrabenh Thank you all!

2025-01-06 20:50 UTC, mathomp4 commented
After talking with @sdrabenh I've changed:

* `@ACTUAL_ATM4OCN` → `@MODELATM`
* `@USE_DATA_ATM4OCN` → `@DATAATM`

I've also talked with @mfmehari and he'll check to make sure the data atm side of this is still working.

2025-01-06 21:31 UTC, mfmehari commented
> After talking with @sdrabenh I've changed:
> 
> * `@ACTUAL_ATM4OCN` → `@MODELATM`
> * `@USE_DATA_ATM4OCN` → `@DATAATM`
> 
> I've also talked with @mfmehari and he'll check to make sure the data atm side of this is still working.

@mathomp4 @sdrabenh I think we need to keep USE_DATA_ATM4OCN ... previously it was DATAATM but after some discussions it was decided to  change it to USE_DATA_ATM4OCN

2025-01-06 22:45 UTC, mathomp4 commented
> > After talking with @sdrabenh I've changed:
> > 
> > * `@ACTUAL_ATM4OCN` → `@MODELATM`
> > * `@USE_DATA_ATM4OCN` → `@DATAATM`
> > 
> > I've also talked with @mfmehari and he'll check to make sure the data atm side of this is still working.
> 
> @mathomp4 @sdrabenh I think we need to keep USE_DATA_ATM4OCN ... previously it was DATAATM but after some discussions it was decided to change it to USE_DATA_ATM4OCN

Okay. I'll re-revert that.

2025-01-06 22:49 UTC, mathomp4 commented
@mfmehari Can you take a look now?

2025-01-06 23:37 UTC, mfmehari commented
> @mfmehari Can you take a look now?
@mathomp4 DataAtm is working ... no issue.

2025-01-07 00:18 UTC, mfmehari commented
> @mfmehari Can you take a look now?

@mathomp4 DataAtm is working.

2025-01-07 21:39 UTC, sdrabenh approved these changes

2025-01-07 21:40 UTC, mathomp4 approved these changes

2025-01-07 21:43 UTC, merged